# Generated by Django 4.0.1 on 2022-01-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=70)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
